//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inverna
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alerta
    {
        public int idalerta { get; set; }
        public int umbralalerta_idumbralalerta { get; set; }
        public double valorlectura { get; set; }
        public System.DateTime fecha { get; set; }
        public string comentarios { get; set; }
    
        public virtual UmbralAlerta UmbralAlerta { get; set; }
    }
}
