//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inverna
{
    using System;
    using System.Collections.Generic;
    
    public partial class Informe
    {
        public int idinforme { get; set; }
        public System.DateTime fecha { get; set; }
        public int usuario_idusuario { get; set; }
        public int tipolectura_idtipolectura { get; set; }
        public string comentarios { get; set; }
    
        public virtual TipoLectura TipoLectura { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
