//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inverna
{
    using System;
    using System.Collections.Generic;
    
    public partial class UmbralAlerta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UmbralAlerta()
        {
            this.Alerta = new HashSet<Alerta>();
        }
    
        public int idumbralalerta { get; set; }
        public int tipolectura_idtipolectura { get; set; }
        public double minimo { get; set; }
        public double maximo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Alerta> Alerta { get; set; }
        public virtual TipoLectura TipoLectura { get; set; }
    }
}
